name = "Solidity"
grammar = "solidity"
path_suffixes = ["sol"]
line_comments = ["/// ", "// "]
tab_size = 4
hard_tabs = false
documentation_comment = { start = "/**", prefix = " * ", end = " */", tab_size = 1 }
